server:
  port: 80

spring:
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    password: nieqin

minio:
  url: http://129.28.131.210:9000
  access-key: nzq
  secret-key: 12345678

mailjet:
  key: 421f456e32ea5567fb56be9fb5847d1a
  secret: dde6f6ded459f2ce4f1469e2a428acb5
  from: 121453698@qq.com


logging:
  level:
    root: info