server:
  port: 80

spring:
  mail:
    host: smtp.huaqiutong.net
    username: adstool@huaqiutong.net
    password: huaqiutongAds.
    default-encoding: UTF-8
    properties:
      mail.smtp:
        port: 465
        auth: true
        ssl.enable: true

  redis:
  # Redis服务器地址
    host: 127.0.0.1
  # Redis服务器连接端口
    port: 6379
