server:
  port: 9999

spring:
  profiles:
    active: dev
#    active: prod

  mail:
    host: smtp.163.com
    port: 465
    username: 16670409213@163.com
    password: sanpang1112
    default-encoding: UTF-8
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      starttls.required: true
      ssl.enable: true
  mvc:
    favicon:
      enabled: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB

minio:
  url: http://minio.sanpang.xyz
  access-key: nzq
  secret-key: 12345678

mailjet:
  key: 421f456e32ea5567fb56be9fb5847d1a
  secret: dde6f6ded459f2ce4f1469e2a428acb5
  from: XinYuGuanLi@sanpang.xyz


ali-sms:
  accessKeyId: 'LTAI4G4CgC8p1NW5gLQFaRKU'
  accessSecret: 'JIW8QVMzM0YuVWNzCpAAq8dqGsfOBA'
  # 模板代码
  templateCode: 'SMS_211493450'
  # 短信签名
  signName: 'Lying'



logging:
  level:
    root: info


